Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Text
Imports System.Windows.Forms
Imports HalconDotNet

Public Enum enumSearchDirection
    LeftToRight = 0
    RightToLeft = 1
    TopToBottom = 2
    BottomToTop = 3
End Enum

Public Class CStraightEdgeTool
    #Region "Member"
    ''' <summary>
    ''' 找尋結果數量
    ''' </summary>
    ''' <remarks></remarks>
    Private m_Count As Int32
    ''' <summary>
    ''' 十字線交點座標
    ''' </summary>
    ''' <remarks></remarks>
    Private m_Point As CLineSegment
    #End Region
    #Region "Construct & Destruct"
    Public Sub New()
        m_Count = 0
        m_Point = New CLineSegment
    End Sub

    Protected Overrides Sub Finalize()
        m_Point = Nothing
        MyBase.Finalize()
    End Sub
    #End Region

    #Region "Property"
    ''' <summary>
    ''' 找尋結果數量
    ''' </summary>
    ''' <value></value>
    ''' <returns></returns>
    ''' <remarks></remarks>
    Public ReadOnly Property Count() As Int32
        Get
            Return m_Count
        End Get
    End Property
    ''' <summary>
    ''' 十字線交點座標
    ''' </summary>
    ''' <value></value>
    ''' <returns></returns>
    ''' <remarks></remarks>
    Public ReadOnly Property Point() As CLineSegment
        Get
            Return m_Point
        End Get
    End Property
    #End Region
    #Region "Methods"
    Public Sub Find(ByRef pSourceImage As CImage, ByRef ImageViewer As ImageDisplay, ByVal Direction As enumSearchDirection)
        ' Local control variables 
        Dim amplitudeThreshold_1st As HTuple = New HTuple
        Dim roiWidthLen2_1st As HTuple = New HTuple
        Dim lineRowStart_Measure_1st As HTuple = New HTuple
        Dim lineColumnStart_Measure_1st As HTuple = New HTuple
        Dim lineRowEnd_Measure_1st As HTuple = New HTuple
        Dim lineColumnEnd_Measure_1st As HTuple = New HTuple
        Dim tmpCtrl_Row_1st As HTuple = New HTuple
        Dim tmpCtrl_Column_1st As HTuple = New HTuple
        Dim tmpCtrl_Dr_1st As HTuple = New HTuple
        Dim tmpCtrl_Dc_1st As HTuple = New HTuple
        Dim tmpCtrl_Phi_1st As HTuple = New HTuple
        Dim tmpCtrl_Len1_1st As HTuple = New HTuple
        Dim tmpCtrl_Len2_1st As HTuple = New HTuple
        Dim msrHandle_Measure_1st As HTuple = New HTuple
        Dim row_Measure_1st As HTuple = New HTuple
        Dim column_Measure_1st As HTuple = New HTuple
        Dim amplitude_Measure_1st As HTuple = New HTuple
        Dim distance_Measure_1st As HTuple = New HTuple

        Dim amplitudeThreshold_2nd As HTuple = New HTuple
        Dim roiWidthLen2_2nd As HTuple = New HTuple
        Dim lineRowStart_Measure_2nd As HTuple = New HTuple
        Dim lineColumnStart_Measure_2nd As HTuple = New HTuple
        Dim lineRowEnd_Measure_2nd As HTuple = New HTuple
        Dim lineColumnEnd_Measure_2nd As HTuple = New HTuple
        Dim tmpCtrl_Row_2nd As HTuple = New HTuple
        Dim tmpCtrl_Column_2nd As HTuple = New HTuple
        Dim tmpCtrl_Dr_2nd As HTuple = New HTuple
        Dim tmpCtrl_Dc_2nd As HTuple = New HTuple
        Dim tmpCtrl_Phi_2nd As HTuple = New HTuple
        Dim tmpCtrl_Len1_2nd As HTuple = New HTuple
        Dim tmpCtrl_Len2_2nd As HTuple = New HTuple
        Dim msrHandle_Measure_2nd As HTuple = New HTuple
        Dim row_Measure_2nd As HTuple = New HTuple
        Dim column_Measure_2nd As HTuple = New HTuple
        Dim amplitude_Measure_2nd As HTuple = New HTuple
        Dim distance_Measure_2nd As HTuple = New HTuple

        Dim amplitudeThreshold_3rd As HTuple = New HTuple
        Dim roiWidthLen2_3rd As HTuple = New HTuple
        Dim lineRowStart_Measure_3rd As HTuple = New HTuple
        Dim lineColumnStart_Measure_3rd As HTuple = New HTuple
        Dim lineRowEnd_Measure_3rd As HTuple = New HTuple
        Dim lineColumnEnd_Measure_3rd As HTuple = New HTuple
        Dim tmpCtrl_Row_3rd As HTuple = New HTuple
        Dim tmpCtrl_Column_3rd As HTuple = New HTuple
        Dim tmpCtrl_Dr_3rd As HTuple = New HTuple
        Dim tmpCtrl_Dc_3rd As HTuple = New HTuple
        Dim tmpCtrl_Phi_3rd As HTuple = New HTuple
        Dim tmpCtrl_Len1_3rd As HTuple = New HTuple
        Dim tmpCtrl_Len2_3rd As HTuple = New HTuple
        Dim msrHandle_Measure_3rd As HTuple = New HTuple
        Dim row_Measure_3rd As HTuple = New HTuple
        Dim column_Measure_3rd As HTuple = New HTuple
        Dim amplitude_Measure_3rd As HTuple = New HTuple
        Dim distance_Measure_3rd As HTuple = New HTuple


        Dim HTuple_Sigma As HTuple = New HTuple(15.2)
        Dim HTuple_Threshold As HTuple = New HTuple(87)
        Dim HTuple_Trarsition As HTuple = New HTuple("positive")
        Dim HTuple_Select As HTuple = New HTuple("first")

        'Measure 01: Code generated by Measure 01
        'Measure 01: Prepare measurement
        amplitudeThreshold_1st = New HTuple(7)
        Select Case Direction
            Case enumSearchDirection.BottomToTop, enumSearchDirection.TopToBottom
                roiWidthLen2_1st = 100 ' pSourceImage.Width
            Case enumSearchDirection.LeftToRight, enumSearchDirection.RightToLeft
                roiWidthLen2_1st = 100 'pSourceImage.Height
        End Select

        'Measure 01: Coordinates for line Measure 01 [0]
        Select Case Direction
            Case enumSearchDirection.TopToBottom
                lineRowStart_Measure_1st = New HTuple(0)
                lineColumnStart_Measure_1st = New HTuple(pSourceImage.Width / 4)
                lineRowEnd_Measure_1st = New HTuple(pSourceImage.Height)
                lineColumnEnd_Measure_1st = New HTuple(pSourceImage.Width / 4)
            Case enumSearchDirection.BottomToTop
                lineRowStart_Measure_1st = New HTuple(pSourceImage.Height)
                lineColumnStart_Measure_1st = New HTuple(pSourceImage.Width / 4)
                lineRowEnd_Measure_1st = New HTuple(0)
                lineColumnEnd_Measure_1st = New HTuple(pSourceImage.Width / 4)
            Case enumSearchDirection.LeftToRight
                lineRowStart_Measure_1st = New HTuple(pSourceImage.Height / 4)
                lineColumnStart_Measure_1st = New HTuple(0)
                lineRowEnd_Measure_1st = New HTuple(pSourceImage.Height / 4)
                lineColumnEnd_Measure_1st = New HTuple(pSourceImage.Width)
            Case enumSearchDirection.RightToLeft
                lineRowStart_Measure_1st = New HTuple(pSourceImage.Height / 4)
                lineColumnStart_Measure_1st = New HTuple(pSourceImage.Width)
                lineRowEnd_Measure_1st = New HTuple(pSourceImage.Height / 4)
                lineColumnEnd_Measure_1st = New HTuple(0)
        End Select

        'Measure 01: Convert coordinates to rectangle2 type
        tmpCtrl_Row_1st = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_1st.TupleAdd(lineRowEnd_Measure_1st))
        tmpCtrl_Column_1st = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_1st.TupleAdd(lineColumnEnd_Measure_1st))
        tmpCtrl_Dr_1st = lineRowStart_Measure_1st.TupleSub(lineRowEnd_Measure_1st)
        tmpCtrl_Dc_1st = lineColumnEnd_Measure_1st.TupleSub(lineColumnStart_Measure_1st)
        tmpCtrl_Phi_1st = tmpCtrl_Dr_1st.TupleAtan2(tmpCtrl_Dc_1st)
        tmpCtrl_Len1_1st = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_1st.TupleMult(tmpCtrl_Dr_1st))).TupleAdd(tmpCtrl_Dc_1st.TupleMult(tmpCtrl_Dc_1st)))).TupleSqrt())
        tmpCtrl_Len2_1st = roiWidthLen2_1st.Clone()
        'Measure 01: Create measure for line Measure 01 [0]
        'Measure 01: Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_1st, tmpCtrl_Column_1st, tmpCtrl_Phi_1st, _
                                          tmpCtrl_Len1_1st, tmpCtrl_Len2_1st, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("nearest_neighbor"), _
                                          msrHandle_Measure_1st)
        'Measure 01: Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_1st, HTuple_Sigma, HTuple_Threshold, HTuple_Trarsition, HTuple_Select, row_Measure_1st, column_Measure_1st, amplitude_Measure_1st, distance_Measure_1st)




        'Measure 01: Code generated by Measure 01
        'Measure 01: Prepare measurement
        amplitudeThreshold_2nd = New HTuple(7)
        Select Case Direction
            Case enumSearchDirection.BottomToTop, enumSearchDirection.TopToBottom
                roiWidthLen2_2nd = 100 'pSourceImage.Width
            Case enumSearchDirection.LeftToRight, enumSearchDirection.RightToLeft
                roiWidthLen2_2nd = 100 'pSourceImage.Height
        End Select

        Select Case Direction
            Case enumSearchDirection.TopToBottom
                lineRowStart_Measure_2nd = New HTuple(0)
                lineColumnStart_Measure_2nd = New HTuple(pSourceImage.Width / 2)
                lineRowEnd_Measure_2nd = New HTuple(pSourceImage.Height)
                lineColumnEnd_Measure_2nd = New HTuple(pSourceImage.Width / 2)
            Case enumSearchDirection.BottomToTop
                lineRowStart_Measure_2nd = New HTuple(pSourceImage.Height)
                lineColumnStart_Measure_2nd = New HTuple(pSourceImage.Width / 2)
                lineRowEnd_Measure_2nd = New HTuple(0)
                lineColumnEnd_Measure_2nd = New HTuple(pSourceImage.Width / 2)
            Case enumSearchDirection.LeftToRight
                lineRowStart_Measure_2nd = New HTuple(pSourceImage.Height / 2)
                lineColumnStart_Measure_2nd = New HTuple(0)
                lineRowEnd_Measure_2nd = New HTuple(pSourceImage.Height / 2)
                lineColumnEnd_Measure_2nd = New HTuple(pSourceImage.Width)
            Case enumSearchDirection.RightToLeft
                lineRowStart_Measure_2nd = New HTuple(pSourceImage.Height / 2)
                lineColumnStart_Measure_2nd = New HTuple(pSourceImage.Width)
                lineRowEnd_Measure_2nd = New HTuple(pSourceImage.Height / 2)
                lineColumnEnd_Measure_2nd = New HTuple(0)
        End Select

        'Measure 01: Convert coordinates to rectangle2 type
        tmpCtrl_Row_2nd = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_2nd.TupleAdd(lineRowEnd_Measure_2nd))
        tmpCtrl_Column_2nd = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_2nd.TupleAdd(lineColumnEnd_Measure_2nd))
        tmpCtrl_Dr_2nd = lineRowStart_Measure_2nd.TupleSub(lineRowEnd_Measure_2nd)
        tmpCtrl_Dc_2nd = lineColumnEnd_Measure_2nd.TupleSub(lineColumnStart_Measure_2nd)
        tmpCtrl_Phi_2nd = tmpCtrl_Dr_2nd.TupleAtan2(tmpCtrl_Dc_2nd)
        tmpCtrl_Len1_2nd = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_2nd.TupleMult(tmpCtrl_Dr_2nd))).TupleAdd(tmpCtrl_Dc_2nd.TupleMult(tmpCtrl_Dc_2nd)))).TupleSqrt())
        tmpCtrl_Len2_2nd = roiWidthLen2_2nd.Clone()
        'Measure 01: Create measure for line Measure 01 [0]
        'Measure 01: Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_2nd, tmpCtrl_Column_2nd, tmpCtrl_Phi_2nd, _
                                          tmpCtrl_Len1_2nd, tmpCtrl_Len2_2nd, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("nearest_neighbor"), _
                                          msrHandle_Measure_2nd)
        'Measure 01: Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_2nd, HTuple_Sigma, HTuple_Threshold, HTuple_Trarsition, HTuple_Select, row_Measure_2nd, column_Measure_2nd, amplitude_Measure_2nd, distance_Measure_2nd)



        'Measure 01: Code generated by Measure 01
        'Measure 01: Prepare measurement
        amplitudeThreshold_3rd = New HTuple(7)
        Select Case Direction
            Case enumSearchDirection.BottomToTop, enumSearchDirection.TopToBottom
                roiWidthLen2_3rd = 100 'pSourceImage.Width
            Case enumSearchDirection.LeftToRight, enumSearchDirection.RightToLeft
                roiWidthLen2_3rd = 100 'pSourceImage.Height
        End Select

        'HOperatorSet.SetSystem(New HTuple("int_zooming"), New HTuple("true"))
        'Measure 01: Coordinates for line Measure 01 [0]
        Select Case Direction
            Case enumSearchDirection.TopToBottom
                lineRowStart_Measure_3rd = New HTuple(0)
                lineColumnStart_Measure_3rd = New HTuple(pSourceImage.Width * 3 / 4)
                lineRowEnd_Measure_3rd = New HTuple(pSourceImage.Height)
                lineColumnEnd_Measure_3rd = New HTuple(pSourceImage.Width * 3 / 4)
            Case enumSearchDirection.BottomToTop
                lineRowStart_Measure_3rd = New HTuple(pSourceImage.Height)
                lineColumnStart_Measure_3rd = New HTuple(pSourceImage.Width * 3 / 4)
                lineRowEnd_Measure_3rd = New HTuple(0)
                lineColumnEnd_Measure_3rd = New HTuple(pSourceImage.Width * 3 / 4)
            Case enumSearchDirection.LeftToRight
                lineRowStart_Measure_3rd = New HTuple(pSourceImage.Height * 3 / 4)
                lineColumnStart_Measure_3rd = New HTuple(0)
                lineRowEnd_Measure_3rd = New HTuple(pSourceImage.Height * 3 / 4)
                lineColumnEnd_Measure_3rd = New HTuple(pSourceImage.Width)
            Case enumSearchDirection.RightToLeft
                lineRowStart_Measure_3rd = New HTuple(pSourceImage.Height * 3 / 4)
                lineColumnStart_Measure_3rd = New HTuple(pSourceImage.Width)
                lineRowEnd_Measure_3rd = New HTuple(pSourceImage.Height * 3 / 4)
                lineColumnEnd_Measure_3rd = New HTuple(0)
        End Select

        'Measure 01: Convert coordinates to rectangle2 type
        tmpCtrl_Row_3rd = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_3rd.TupleAdd(lineRowEnd_Measure_3rd))
        tmpCtrl_Column_3rd = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_3rd.TupleAdd(lineColumnEnd_Measure_3rd))
        tmpCtrl_Dr_3rd = lineRowStart_Measure_3rd.TupleSub(lineRowEnd_Measure_3rd)
        tmpCtrl_Dc_3rd = lineColumnEnd_Measure_3rd.TupleSub(lineColumnStart_Measure_3rd)
        tmpCtrl_Phi_3rd = tmpCtrl_Dr_3rd.TupleAtan2(tmpCtrl_Dc_3rd)
        tmpCtrl_Len1_3rd = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_3rd.TupleMult(tmpCtrl_Dr_3rd))).TupleAdd(tmpCtrl_Dc_3rd.TupleMult(tmpCtrl_Dc_3rd)))).TupleSqrt())
        tmpCtrl_Len2_3rd = roiWidthLen2_3rd.Clone()
        'Measure 01: Create measure for line Measure 01 [0]
        'Measure 01: Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_3rd, tmpCtrl_Column_3rd, tmpCtrl_Phi_3rd, _
                                          tmpCtrl_Len1_3rd, tmpCtrl_Len2_3rd, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("nearest_neighbor"), _
                                          msrHandle_Measure_3rd)

        'Measure 01: Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_3rd, HTuple_Sigma, HTuple_Threshold, HTuple_Trarsition, HTuple_Select, row_Measure_3rd, column_Measure_3rd, amplitude_Measure_3rd, distance_Measure_3rd)


        'Measure 01: Do something with the results
        m_Count = 0
        If (row_Measure_1st.Length() > 0) AndAlso (row_Measure_2nd.Length() > 0) AndAlso (row_Measure_3rd.Length() > 0) Then
            Select Case Direction
                Case enumSearchDirection.BottomToTop, enumSearchDirection.TopToBottom
                    Call m_Point.SetOriginEndPos(0, (row_Measure_1st.D() + row_Measure_2nd.D() + row_Measure_3rd.D()) / 3, pSourceImage.Width, (row_Measure_1st.D() + row_Measure_2nd.D() + row_Measure_3rd.D()) / 3)
                Case enumSearchDirection.LeftToRight, enumSearchDirection.RightToLeft
                    Call m_Point.SetOriginEndPos((column_Measure_1st.D() + column_Measure_2nd.D() + column_Measure_3rd.D()) / 3, 0, (column_Measure_1st.D() + column_Measure_2nd.D() + column_Measure_3rd.D()) / 3, pSourceImage.Height)
            End Select
            m_Count = m_Count + 1
        End If
        'Measure 01: Clear measure when done
        HOperatorSet.CloseMeasure(msrHandle_Measure_1st)
        HOperatorSet.CloseMeasure(msrHandle_Measure_2nd)
        HOperatorSet.CloseMeasure(msrHandle_Measure_3rd)
    End Sub

    Public Sub Find1(ByRef pSourceImage As CImage, ByRef ImageViewer As ImageDisplay, ByVal Direction As enumSearchDirection)
        ' Local control variables 
        Dim amplitudeThreshold_1st As HTuple = New HTuple
        Dim roiWidthLen2_1st As HTuple = New HTuple
        Dim lineRowStart_Measure_1st As HTuple = New HTuple
        Dim lineColumnStart_Measure_1st As HTuple = New HTuple
        Dim lineRowEnd_Measure_1st As HTuple = New HTuple
        Dim lineColumnEnd_Measure_1st As HTuple = New HTuple
        Dim tmpCtrl_Row_1st As HTuple = New HTuple
        Dim tmpCtrl_Column_1st As HTuple = New HTuple
        Dim tmpCtrl_Dr_1st As HTuple = New HTuple
        Dim tmpCtrl_Dc_1st As HTuple = New HTuple
        Dim tmpCtrl_Phi_1st As HTuple = New HTuple
        Dim tmpCtrl_Len1_1st As HTuple = New HTuple
        Dim tmpCtrl_Len2_1st As HTuple = New HTuple
        Dim msrHandle_Measure_1st As HTuple = New HTuple
        Dim row_Measure_1st As HTuple = New HTuple
        Dim column_Measure_1st As HTuple = New HTuple
        Dim amplitude_Measure_1st As HTuple = New HTuple
        Dim distance_Measure_1st As HTuple = New HTuple

        Dim amplitudeThreshold_2nd As HTuple = New HTuple
        Dim roiWidthLen2_2nd As HTuple = New HTuple
        Dim lineRowStart_Measure_2nd As HTuple = New HTuple
        Dim lineColumnStart_Measure_2nd As HTuple = New HTuple
        Dim lineRowEnd_Measure_2nd As HTuple = New HTuple
        Dim lineColumnEnd_Measure_2nd As HTuple = New HTuple
        Dim tmpCtrl_Row_2nd As HTuple = New HTuple
        Dim tmpCtrl_Column_2nd As HTuple = New HTuple
        Dim tmpCtrl_Dr_2nd As HTuple = New HTuple
        Dim tmpCtrl_Dc_2nd As HTuple = New HTuple
        Dim tmpCtrl_Phi_2nd As HTuple = New HTuple
        Dim tmpCtrl_Len1_2nd As HTuple = New HTuple
        Dim tmpCtrl_Len2_2nd As HTuple = New HTuple
        Dim msrHandle_Measure_2nd As HTuple = New HTuple
        Dim row_Measure_2nd As HTuple = New HTuple
        Dim column_Measure_2nd As HTuple = New HTuple
        Dim amplitude_Measure_2nd As HTuple = New HTuple
        Dim distance_Measure_2nd As HTuple = New HTuple

        Dim amplitudeThreshold_3rd As HTuple = New HTuple
        Dim roiWidthLen2_3rd As HTuple = New HTuple
        Dim lineRowStart_Measure_3rd As HTuple = New HTuple
        Dim lineColumnStart_Measure_3rd As HTuple = New HTuple
        Dim lineRowEnd_Measure_3rd As HTuple = New HTuple
        Dim lineColumnEnd_Measure_3rd As HTuple = New HTuple
        Dim tmpCtrl_Row_3rd As HTuple = New HTuple
        Dim tmpCtrl_Column_3rd As HTuple = New HTuple
        Dim tmpCtrl_Dr_3rd As HTuple = New HTuple
        Dim tmpCtrl_Dc_3rd As HTuple = New HTuple
        Dim tmpCtrl_Phi_3rd As HTuple = New HTuple
        Dim tmpCtrl_Len1_3rd As HTuple = New HTuple
        Dim tmpCtrl_Len2_3rd As HTuple = New HTuple
        Dim msrHandle_Measure_3rd As HTuple = New HTuple
        Dim row_Measure_3rd As HTuple = New HTuple
        Dim column_Measure_3rd As HTuple = New HTuple
        Dim amplitude_Measure_3rd As HTuple = New HTuple
        Dim distance_Measure_3rd As HTuple = New HTuple


        Dim HTuple_Sigma As HTuple = New HTuple(15.2)
        Dim HTuple_Threshold As HTuple = New HTuple(87)
        Dim HTuple_Trarsition As HTuple = New HTuple("positive")
        Dim HTuple_Select As HTuple = New HTuple("first")

        'Measure 01: Code generated by Measure 01
        'Measure 01: Prepare measurement
        amplitudeThreshold_1st = New HTuple(15)
        Select Case Direction
            Case enumSearchDirection.BottomToTop, enumSearchDirection.TopToBottom
                roiWidthLen2_1st = 100 ' pSourceImage.Width
            Case enumSearchDirection.LeftToRight, enumSearchDirection.RightToLeft
                roiWidthLen2_1st = 100 'pSourceImage.Height
        End Select

        'Measure 01: Coordinates for line Measure 01 [0]
        Select Case Direction
            Case enumSearchDirection.TopToBottom
                lineRowStart_Measure_1st = New HTuple(0)
                lineColumnStart_Measure_1st = New HTuple(pSourceImage.Width / 4)
                lineRowEnd_Measure_1st = New HTuple(pSourceImage.Height)
                lineColumnEnd_Measure_1st = New HTuple(pSourceImage.Width / 4)
            Case enumSearchDirection.BottomToTop
                lineRowStart_Measure_1st = New HTuple(pSourceImage.Height)
                lineColumnStart_Measure_1st = New HTuple(pSourceImage.Width / 4)
                lineRowEnd_Measure_1st = New HTuple(0)
                lineColumnEnd_Measure_1st = New HTuple(pSourceImage.Width / 4)
            Case enumSearchDirection.LeftToRight
                lineRowStart_Measure_1st = New HTuple(pSourceImage.Height / 4)
                lineColumnStart_Measure_1st = New HTuple(0)
                lineRowEnd_Measure_1st = New HTuple(pSourceImage.Height / 4)
                lineColumnEnd_Measure_1st = New HTuple(pSourceImage.Width)
            Case enumSearchDirection.RightToLeft
                lineRowStart_Measure_1st = New HTuple(pSourceImage.Height / 4)
                lineColumnStart_Measure_1st = New HTuple(pSourceImage.Width)
                lineRowEnd_Measure_1st = New HTuple(pSourceImage.Height / 4)
                lineColumnEnd_Measure_1st = New HTuple(0)
        End Select

        'Measure 01: Convert coordinates to rectangle2 type
        tmpCtrl_Row_1st = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_1st.TupleAdd(lineRowEnd_Measure_1st))
        tmpCtrl_Column_1st = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_1st.TupleAdd(lineColumnEnd_Measure_1st))
        tmpCtrl_Dr_1st = lineRowStart_Measure_1st.TupleSub(lineRowEnd_Measure_1st)
        tmpCtrl_Dc_1st = lineColumnEnd_Measure_1st.TupleSub(lineColumnStart_Measure_1st)
        tmpCtrl_Phi_1st = tmpCtrl_Dr_1st.TupleAtan2(tmpCtrl_Dc_1st)
        tmpCtrl_Len1_1st = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_1st.TupleMult(tmpCtrl_Dr_1st))).TupleAdd(tmpCtrl_Dc_1st.TupleMult(tmpCtrl_Dc_1st)))).TupleSqrt())
        tmpCtrl_Len2_1st = roiWidthLen2_1st.Clone()
        'Measure 01: Create measure for line Measure 01 [0]
        'Measure 01: Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_1st, tmpCtrl_Column_1st, tmpCtrl_Phi_1st, _
                                          tmpCtrl_Len1_1st, tmpCtrl_Len2_1st, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("nearest_neighbor"), _
                                          msrHandle_Measure_1st)
        'Measure 01: Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_1st, HTuple_Sigma, HTuple_Threshold, HTuple_Trarsition, HTuple_Select, row_Measure_1st, column_Measure_1st, amplitude_Measure_1st, distance_Measure_1st)




        'Measure 01: Code generated by Measure 01
        'Measure 01: Prepare measurement
        amplitudeThreshold_2nd = New HTuple(15)
        Select Case Direction
            Case enumSearchDirection.BottomToTop, enumSearchDirection.TopToBottom
                roiWidthLen2_2nd = 100 'pSourceImage.Width
            Case enumSearchDirection.LeftToRight, enumSearchDirection.RightToLeft
                roiWidthLen2_2nd = 100 'pSourceImage.Height
        End Select

        Select Case Direction
            Case enumSearchDirection.TopToBottom
                lineRowStart_Measure_2nd = New HTuple(0)
                lineColumnStart_Measure_2nd = New HTuple(pSourceImage.Width / 2)
                lineRowEnd_Measure_2nd = New HTuple(pSourceImage.Height)
                lineColumnEnd_Measure_2nd = New HTuple(pSourceImage.Width / 2)
            Case enumSearchDirection.BottomToTop
                lineRowStart_Measure_2nd = New HTuple(pSourceImage.Height)
                lineColumnStart_Measure_2nd = New HTuple(pSourceImage.Width / 2)
                lineRowEnd_Measure_2nd = New HTuple(0)
                lineColumnEnd_Measure_2nd = New HTuple(pSourceImage.Width / 2)
            Case enumSearchDirection.LeftToRight
                lineRowStart_Measure_2nd = New HTuple(pSourceImage.Height / 2)
                lineColumnStart_Measure_2nd = New HTuple(0)
                lineRowEnd_Measure_2nd = New HTuple(pSourceImage.Height / 2)
                lineColumnEnd_Measure_2nd = New HTuple(pSourceImage.Width)
            Case enumSearchDirection.RightToLeft
                lineRowStart_Measure_2nd = New HTuple(pSourceImage.Height / 2)
                lineColumnStart_Measure_2nd = New HTuple(pSourceImage.Width)
                lineRowEnd_Measure_2nd = New HTuple(pSourceImage.Height / 2)
                lineColumnEnd_Measure_2nd = New HTuple(0)
        End Select

        'Measure 01: Convert coordinates to rectangle2 type
        tmpCtrl_Row_2nd = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_2nd.TupleAdd(lineRowEnd_Measure_2nd))
        tmpCtrl_Column_2nd = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_2nd.TupleAdd(lineColumnEnd_Measure_2nd))
        tmpCtrl_Dr_2nd = lineRowStart_Measure_2nd.TupleSub(lineRowEnd_Measure_2nd)
        tmpCtrl_Dc_2nd = lineColumnEnd_Measure_2nd.TupleSub(lineColumnStart_Measure_2nd)
        tmpCtrl_Phi_2nd = tmpCtrl_Dr_2nd.TupleAtan2(tmpCtrl_Dc_2nd)
        tmpCtrl_Len1_2nd = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_2nd.TupleMult(tmpCtrl_Dr_2nd))).TupleAdd(tmpCtrl_Dc_2nd.TupleMult(tmpCtrl_Dc_2nd)))).TupleSqrt())
        tmpCtrl_Len2_2nd = roiWidthLen2_2nd.Clone()
        'Measure 01: Create measure for line Measure 01 [0]
        'Measure 01: Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_2nd, tmpCtrl_Column_2nd, tmpCtrl_Phi_2nd, _
                                          tmpCtrl_Len1_2nd, tmpCtrl_Len2_2nd, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("nearest_neighbor"), _
                                          msrHandle_Measure_2nd)
        'Measure 01: Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_2nd, HTuple_Sigma, HTuple_Threshold, HTuple_Trarsition, HTuple_Select, row_Measure_2nd, column_Measure_2nd, amplitude_Measure_2nd, distance_Measure_2nd)



        'Measure 01: Code generated by Measure 01
        'Measure 01: Prepare measurement
        amplitudeThreshold_3rd = New HTuple(15)
        Select Case Direction
            Case enumSearchDirection.BottomToTop, enumSearchDirection.TopToBottom
                roiWidthLen2_3rd = 100 'pSourceImage.Width
            Case enumSearchDirection.LeftToRight, enumSearchDirection.RightToLeft
                roiWidthLen2_3rd = 100 'pSourceImage.Height
        End Select

        'HOperatorSet.SetSystem(New HTuple("int_zooming"), New HTuple("true"))
        'Measure 01: Coordinates for line Measure 01 [0]
        Select Case Direction
            Case enumSearchDirection.TopToBottom
                lineRowStart_Measure_3rd = New HTuple(0)
                lineColumnStart_Measure_3rd = New HTuple(pSourceImage.Width * 3 / 4)
                lineRowEnd_Measure_3rd = New HTuple(pSourceImage.Height)
                lineColumnEnd_Measure_3rd = New HTuple(pSourceImage.Width * 3 / 4)
            Case enumSearchDirection.BottomToTop
                lineRowStart_Measure_3rd = New HTuple(pSourceImage.Height)
                lineColumnStart_Measure_3rd = New HTuple(pSourceImage.Width * 3 / 4)
                lineRowEnd_Measure_3rd = New HTuple(0)
                lineColumnEnd_Measure_3rd = New HTuple(pSourceImage.Width * 3 / 4)
            Case enumSearchDirection.LeftToRight
                lineRowStart_Measure_3rd = New HTuple(pSourceImage.Height * 3 / 4)
                lineColumnStart_Measure_3rd = New HTuple(0)
                lineRowEnd_Measure_3rd = New HTuple(pSourceImage.Height * 3 / 4)
                lineColumnEnd_Measure_3rd = New HTuple(pSourceImage.Width)
            Case enumSearchDirection.RightToLeft
                lineRowStart_Measure_3rd = New HTuple(pSourceImage.Height * 3 / 4)
                lineColumnStart_Measure_3rd = New HTuple(pSourceImage.Width)
                lineRowEnd_Measure_3rd = New HTuple(pSourceImage.Height * 3 / 4)
                lineColumnEnd_Measure_3rd = New HTuple(0)
        End Select

        'Measure 01: Convert coordinates to rectangle2 type
        tmpCtrl_Row_3rd = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_3rd.TupleAdd(lineRowEnd_Measure_3rd))
        tmpCtrl_Column_3rd = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_3rd.TupleAdd(lineColumnEnd_Measure_3rd))
        tmpCtrl_Dr_3rd = lineRowStart_Measure_3rd.TupleSub(lineRowEnd_Measure_3rd)
        tmpCtrl_Dc_3rd = lineColumnEnd_Measure_3rd.TupleSub(lineColumnStart_Measure_3rd)
        tmpCtrl_Phi_3rd = tmpCtrl_Dr_3rd.TupleAtan2(tmpCtrl_Dc_3rd)
        tmpCtrl_Len1_3rd = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_3rd.TupleMult(tmpCtrl_Dr_3rd))).TupleAdd(tmpCtrl_Dc_3rd.TupleMult(tmpCtrl_Dc_3rd)))).TupleSqrt())
        tmpCtrl_Len2_3rd = roiWidthLen2_3rd.Clone()
        'Measure 01: Create measure for line Measure 01 [0]
        'Measure 01: Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_3rd, tmpCtrl_Column_3rd, tmpCtrl_Phi_3rd, _
                                          tmpCtrl_Len1_3rd, tmpCtrl_Len2_3rd, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("nearest_neighbor"), _
                                          msrHandle_Measure_3rd)

        'Measure 01: Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_3rd, HTuple_Sigma, HTuple_Threshold, HTuple_Trarsition, HTuple_Select, row_Measure_3rd, column_Measure_3rd, amplitude_Measure_3rd, distance_Measure_3rd)


        'Measure 01: Do something with the results
        m_Count = 0
        If (row_Measure_1st.Length() > 0) AndAlso (row_Measure_2nd.Length() > 0) AndAlso (row_Measure_3rd.Length() > 0) Then
            Select Case Direction
                Case enumSearchDirection.BottomToTop, enumSearchDirection.TopToBottom
                    Call m_Point.SetOriginEndPos(0, (row_Measure_1st.D() + row_Measure_2nd.D() + row_Measure_3rd.D()) / 3, pSourceImage.Width, (row_Measure_1st.D() + row_Measure_2nd.D() + row_Measure_3rd.D()) / 3)
                Case enumSearchDirection.LeftToRight, enumSearchDirection.RightToLeft
                    Call m_Point.SetOriginEndPos((column_Measure_1st.D() + column_Measure_2nd.D() + column_Measure_3rd.D()) / 3, 0, (column_Measure_1st.D() + column_Measure_2nd.D() + column_Measure_3rd.D()) / 3, pSourceImage.Height)
            End Select
            m_Count = m_Count + 1
        End If
        'Measure 01: Clear measure when done
        HOperatorSet.CloseMeasure(msrHandle_Measure_1st)
        HOperatorSet.CloseMeasure(msrHandle_Measure_2nd)
        HOperatorSet.CloseMeasure(msrHandle_Measure_3rd)
    End Sub

    Public Sub FindReticle(ByRef pSourceImage As CImage, ByVal CentraX As Double, ByVal CentraY As Double, ByRef X1 As Double, ByRef Y1 As Double, ByRef X2 As Double, ByRef Y2 As Double)
        Dim amplitudeThreshold_1st As HTuple = New HTuple 'amplitude門檻值
        Dim roiWidthLen2_1st As HTuple = New HTuple 'ROI寬度 實際大小要放大兩倍
        Dim lineRowStart_Measure_1st As HTuple = New HTuple '線段ROW起始
        Dim lineColumnStart_Measure_1st As HTuple = New HTuple '線段COLUMN起始
        Dim lineRowEnd_Measure_1st As HTuple = New HTuple '線段ROW終點
        Dim lineColumnEnd_Measure_1st As HTuple = New HTuple '線段COLUMN終點
        Dim tmpCtrl_Row_1st As HTuple = New HTuple
        Dim tmpCtrl_Column_1st As HTuple = New HTuple
        Dim tmpCtrl_Dr_1st As HTuple = New HTuple
        Dim tmpCtrl_Dc_1st As HTuple = New HTuple
        Dim tmpCtrl_Phi_1st As HTuple = New HTuple
        Dim tmpCtrl_Len1_1st As HTuple = New HTuple
        Dim tmpCtrl_Len2_1st As HTuple = New HTuple
        Dim msrHandle_Measure_1st As HTuple = New HTuple
        Dim row_Measure_1st As HTuple = New HTuple
        Dim column_Measure_1st As HTuple = New HTuple
        Dim amplitude_Measure_1st As HTuple = New HTuple
        Dim distance_Measure_1st As HTuple = New HTuple

        Dim amplitudeThreshold_2nd As HTuple = New HTuple
        Dim roiWidthLen2_2nd As HTuple = New HTuple
        Dim lineRowStart_Measure_2nd As HTuple = New HTuple
        Dim lineColumnStart_Measure_2nd As HTuple = New HTuple
        Dim lineRowEnd_Measure_2nd As HTuple = New HTuple
        Dim lineColumnEnd_Measure_2nd As HTuple = New HTuple
        Dim tmpCtrl_Row_2nd As HTuple = New HTuple
        Dim tmpCtrl_Column_2nd As HTuple = New HTuple
        Dim tmpCtrl_Dr_2nd As HTuple = New HTuple
        Dim tmpCtrl_Dc_2nd As HTuple = New HTuple
        Dim tmpCtrl_Phi_2nd As HTuple = New HTuple
        Dim tmpCtrl_Len1_2nd As HTuple = New HTuple
        Dim tmpCtrl_Len2_2nd As HTuple = New HTuple
        Dim msrHandle_Measure_2nd As HTuple = New HTuple
        Dim row_Measure_2nd As HTuple = New HTuple
        Dim column_Measure_2nd As HTuple = New HTuple
        Dim amplitude_Measure_2nd As HTuple = New HTuple
        Dim distance_Measure_2nd As HTuple = New HTuple

        Dim amplitudeThreshold_3rd As HTuple = New HTuple
        Dim roiWidthLen2_3rd As HTuple = New HTuple
        Dim lineRowStart_Measure_3rd As HTuple = New HTuple
        Dim lineColumnStart_Measure_3rd As HTuple = New HTuple
        Dim lineRowEnd_Measure_3rd As HTuple = New HTuple
        Dim lineColumnEnd_Measure_3rd As HTuple = New HTuple
        Dim tmpCtrl_Row_3rd As HTuple = New HTuple
        Dim tmpCtrl_Column_3rd As HTuple = New HTuple
        Dim tmpCtrl_Dr_3rd As HTuple = New HTuple
        Dim tmpCtrl_Dc_3rd As HTuple = New HTuple
        Dim tmpCtrl_Phi_3rd As HTuple = New HTuple
        Dim tmpCtrl_Len1_3rd As HTuple = New HTuple
        Dim tmpCtrl_Len2_3rd As HTuple = New HTuple
        Dim msrHandle_Measure_3rd As HTuple = New HTuple
        Dim row_Measure_3rd As HTuple = New HTuple
        Dim column_Measure_3rd As HTuple = New HTuple
        Dim amplitude_Measure_3rd As HTuple = New HTuple
        Dim distance_Measure_3rd As HTuple = New HTuple


        Dim amplitudeThreshold_4th As HTuple = New HTuple
        Dim roiWidthLen2_4th As HTuple = New HTuple
        Dim lineRowStart_Measure_4th As HTuple = New HTuple
        Dim lineColumnStart_Measure_4th As HTuple = New HTuple
        Dim lineRowEnd_Measure_4th As HTuple = New HTuple
        Dim lineColumnEnd_Measure_4th As HTuple = New HTuple
        Dim tmpCtrl_Row_4th As HTuple = New HTuple
        Dim tmpCtrl_Column_4th As HTuple = New HTuple
        Dim tmpCtrl_Dr_4th As HTuple = New HTuple
        Dim tmpCtrl_Dc_4th As HTuple = New HTuple
        Dim tmpCtrl_Phi_4th As HTuple = New HTuple
        Dim tmpCtrl_Len1_4th As HTuple = New HTuple
        Dim tmpCtrl_Len2_4th As HTuple = New HTuple
        Dim msrHandle_Measure_4th As HTuple = New HTuple
        Dim row_Measure_4th As HTuple = New HTuple
        Dim column_Measure_4th As HTuple = New HTuple
        Dim amplitude_Measure_4th As HTuple = New HTuple
        Dim distance_Measure_4th As HTuple = New HTuple

        'Prepare measurement
        amplitudeThreshold_1st = New HTuple(10)
        roiWidthLen2_1st = pSourceImage.Width / 8

        '先往上找
        'Coordinates for line Measure
        lineRowStart_Measure_1st = New HTuple(CentraY - 25)
        lineColumnStart_Measure_1st = New HTuple(CentraX + pSourceImage.Width / 8)
        lineRowEnd_Measure_1st = New HTuple(CentraY + 25)
        lineColumnEnd_Measure_1st = New HTuple(CentraX + pSourceImage.Width / 8)


        'Convert coordinates to rectangle2 type
        tmpCtrl_Row_1st = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_1st.TupleAdd(lineRowEnd_Measure_1st))
        tmpCtrl_Column_1st = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_1st.TupleAdd(lineColumnEnd_Measure_1st))
        tmpCtrl_Dr_1st = lineRowStart_Measure_1st.TupleSub(lineRowEnd_Measure_1st)
        tmpCtrl_Dc_1st = lineColumnEnd_Measure_1st.TupleSub(lineColumnStart_Measure_1st)
        tmpCtrl_Phi_1st = tmpCtrl_Dr_1st.TupleAtan2(tmpCtrl_Dc_1st)
        tmpCtrl_Len1_1st = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_1st.TupleMult(tmpCtrl_Dr_1st))).TupleAdd(tmpCtrl_Dc_1st.TupleMult(tmpCtrl_Dc_1st)))).TupleSqrt())
        tmpCtrl_Len2_1st = roiWidthLen2_1st.Clone()
        'Create measure for line Measure
        'Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_1st, tmpCtrl_Column_1st, tmpCtrl_Phi_1st, _
                                          tmpCtrl_Len1_1st, tmpCtrl_Len2_1st, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("bicubic"), _
                                          msrHandle_Measure_1st)
        'Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_1st, New HTuple(2), amplitudeThreshold_1st, New HTuple("negative"), New HTuple("first"), row_Measure_1st, column_Measure_1st, amplitude_Measure_1st, distance_Measure_1st)
        If amplitudeThreshold_1st.Length = 0 Then
            amplitudeThreshold_1st = New HTuple(7)
            HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_1st, New HTuple(2), amplitudeThreshold_1st, New HTuple("negative"), New HTuple("first"), row_Measure_1st, column_Measure_1st, amplitude_Measure_1st, distance_Measure_1st)
        End If
        If amplitudeThreshold_1st.Length = 0 Then
            amplitudeThreshold_1st = New HTuple(5)
            HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_1st, New HTuple(2), amplitudeThreshold_1st, New HTuple("negative"), New HTuple("first"), row_Measure_1st, column_Measure_1st, amplitude_Measure_1st, distance_Measure_1st)
        End If

        'Prepare measurement
        amplitudeThreshold_2nd = New HTuple(10)
        roiWidthLen2_2nd = pSourceImage.Width / 8
        '往下找
        'Coordinates for line Measure
        lineRowStart_Measure_2nd = New HTuple(CentraY + 25)
        lineColumnStart_Measure_2nd = New HTuple(CentraX - pSourceImage.Width / 16)
        lineRowEnd_Measure_2nd = New HTuple(CentraY - 25)
        lineColumnEnd_Measure_2nd = New HTuple(CentraX - pSourceImage.Width / 16)


        'Convert coordinates to rectangle2 type
        tmpCtrl_Row_2nd = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_2nd.TupleAdd(lineRowEnd_Measure_2nd))
        tmpCtrl_Column_2nd = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_2nd.TupleAdd(lineColumnEnd_Measure_2nd))
        tmpCtrl_Dr_2nd = lineRowStart_Measure_2nd.TupleSub(lineRowEnd_Measure_2nd)
        tmpCtrl_Dc_2nd = lineColumnEnd_Measure_2nd.TupleSub(lineColumnStart_Measure_2nd)
        tmpCtrl_Phi_2nd = tmpCtrl_Dr_2nd.TupleAtan2(tmpCtrl_Dc_2nd)
        tmpCtrl_Len1_2nd = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_2nd.TupleMult(tmpCtrl_Dr_2nd))).TupleAdd(tmpCtrl_Dc_2nd.TupleMult(tmpCtrl_Dc_2nd)))).TupleSqrt())
        tmpCtrl_Len2_2nd = roiWidthLen2_2nd.Clone()
        'Create measure for line Measure
        'Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_2nd, tmpCtrl_Column_2nd, tmpCtrl_Phi_2nd, _
                                          tmpCtrl_Len1_2nd, tmpCtrl_Len2_2nd, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("bicubic"), _
                                          msrHandle_Measure_2nd)
        'Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_2nd, New HTuple(2), amplitudeThreshold_2nd, New HTuple("negative"), New HTuple("first"), row_Measure_2nd, column_Measure_2nd, amplitude_Measure_2nd, distance_Measure_2nd)

        If column_Measure_2nd.Length = 0 Then
            amplitudeThreshold_2nd = New HTuple(7) '
            HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_2nd, New HTuple(2), amplitudeThreshold_2nd, New HTuple("negative"), New HTuple("first"), row_Measure_2nd, column_Measure_2nd, amplitude_Measure_2nd, distance_Measure_2nd)
        End If
        If column_Measure_2nd.Length = 0 Then
            amplitudeThreshold_2nd = New HTuple(5) '
            HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_2nd, New HTuple(2), amplitudeThreshold_2nd, New HTuple("negative"), New HTuple("first"), row_Measure_2nd, column_Measure_2nd, amplitude_Measure_2nd, distance_Measure_2nd)
        End If


        'Prepare measurement
        amplitudeThreshold_3rd = New HTuple(10)
        roiWidthLen2_3rd = pSourceImage.Height / 8
        '往左找
        'Coordinates for line Measure
        lineRowStart_Measure_3rd = New HTuple(CentraY - pSourceImage.Height / 8)
        lineColumnStart_Measure_3rd = New HTuple(CentraX - 25)
        lineRowEnd_Measure_3rd = New HTuple(CentraY - pSourceImage.Height / 8)
        lineColumnEnd_Measure_3rd = New HTuple(CentraX + 25)


        'Convert coordinates to rectangle2 type
        tmpCtrl_Row_3rd = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_3rd.TupleAdd(lineRowEnd_Measure_3rd))
        tmpCtrl_Column_3rd = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_3rd.TupleAdd(lineColumnEnd_Measure_3rd))
        tmpCtrl_Dr_3rd = lineRowStart_Measure_3rd.TupleSub(lineRowEnd_Measure_3rd)
        tmpCtrl_Dc_3rd = lineColumnEnd_Measure_3rd.TupleSub(lineColumnStart_Measure_3rd)
        tmpCtrl_Phi_3rd = tmpCtrl_Dr_3rd.TupleAtan2(tmpCtrl_Dc_3rd)
        tmpCtrl_Len1_3rd = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_3rd.TupleMult(tmpCtrl_Dr_3rd))).TupleAdd(tmpCtrl_Dc_3rd.TupleMult(tmpCtrl_Dc_3rd)))).TupleSqrt())
        tmpCtrl_Len2_3rd = roiWidthLen2_3rd.Clone()
        'Create measure for line Measure
        'Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_3rd, tmpCtrl_Column_3rd, tmpCtrl_Phi_3rd, _
                                          tmpCtrl_Len1_3rd, tmpCtrl_Len2_3rd, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("bicubic"), _
                                          msrHandle_Measure_3rd)
        'Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_3rd, New HTuple(2), amplitudeThreshold_3rd, New HTuple("negative"), New HTuple("first"), row_Measure_3rd, column_Measure_3rd, amplitude_Measure_3rd, distance_Measure_3rd)
        If amplitudeThreshold_3rd.Length = 0 Then
            amplitudeThreshold_3rd = New HTuple(7)
            HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_3rd, New HTuple(2), amplitudeThreshold_3rd, New HTuple("negative"), New HTuple("first"), row_Measure_3rd, column_Measure_3rd, amplitude_Measure_3rd, distance_Measure_3rd)
        End If
        If amplitudeThreshold_3rd.Length = 0 Then
            amplitudeThreshold_3rd = New HTuple(5)
            HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_3rd, New HTuple(2), amplitudeThreshold_3rd, New HTuple("negative"), New HTuple("first"), row_Measure_3rd, column_Measure_3rd, amplitude_Measure_3rd, distance_Measure_3rd)
        End If

        'Prepare measurement
        amplitudeThreshold_4th = New HTuple(10)
        roiWidthLen2_4th = pSourceImage.Height / 8
        '往右找
        'Coordinates for line Measure
        lineRowStart_Measure_4th = New HTuple(CentraY + pSourceImage.Height / 8)
        lineColumnStart_Measure_4th = New HTuple(CentraX + 25)
        lineRowEnd_Measure_4th = New HTuple(CentraY + pSourceImage.Height / 8)
        lineColumnEnd_Measure_4th = New HTuple(CentraX - 25)


        'Convert coordinates to rectangle2 type
        tmpCtrl_Row_4th = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_4th.TupleAdd(lineRowEnd_Measure_4th))
        tmpCtrl_Column_4th = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_4th.TupleAdd(lineColumnEnd_Measure_4th))
        tmpCtrl_Dr_4th = lineRowStart_Measure_4th.TupleSub(lineRowEnd_Measure_4th)
        tmpCtrl_Dc_4th = lineColumnEnd_Measure_4th.TupleSub(lineColumnStart_Measure_4th)
        tmpCtrl_Phi_4th = tmpCtrl_Dr_4th.TupleAtan2(tmpCtrl_Dc_4th)
        tmpCtrl_Len1_4th = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_4th.TupleMult(tmpCtrl_Dr_4th))).TupleAdd(tmpCtrl_Dc_4th.TupleMult(tmpCtrl_Dc_4th)))).TupleSqrt())
        tmpCtrl_Len2_4th = roiWidthLen2_4th.Clone()
        'Create measure for line Measure
        'Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_4th, tmpCtrl_Column_4th, tmpCtrl_Phi_4th, _
                                          tmpCtrl_Len1_4th, tmpCtrl_Len2_4th, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("bicubic"), _
                                          msrHandle_Measure_4th)
        'Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_4th, New HTuple(2), amplitudeThreshold_4th, New HTuple("negative"), New HTuple("first"), row_Measure_4th, column_Measure_4th, amplitude_Measure_4th, distance_Measure_4th)
        If amplitudeThreshold_4th.Length = 0 Then
            amplitudeThreshold_4th = New HTuple(7)
            HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_4th, New HTuple(2), amplitudeThreshold_4th, New HTuple("negative"), New HTuple("first"), row_Measure_4th, column_Measure_4th, amplitude_Measure_4th, distance_Measure_4th)
        End If
        If amplitudeThreshold_4th.Length = 0 Then
            amplitudeThreshold_4th = New HTuple(5)
            HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_4th, New HTuple(2), amplitudeThreshold_4th, New HTuple("negative"), New HTuple("first"), row_Measure_4th, column_Measure_4th, amplitude_Measure_4th, distance_Measure_4th)
        End If

        'Do something with the results
        m_Count = 0
        If (row_Measure_1st.Length() > 0) AndAlso (row_Measure_2nd.Length() > 0) AndAlso (row_Measure_3rd.Length() > 0) AndAlso (row_Measure_4th.Length() > 0) Then
            Call m_Point.SetOriginEndPos(column_Measure_3rd.D(), row_Measure_1st.D(), column_Measure_4th.D(), row_Measure_2nd.D())
            Y1 = row_Measure_1st.D()
            X1 = column_Measure_3rd.D()
            Y2 = row_Measure_2nd.D()
            X2 = column_Measure_4th.D()
            m_Count = m_Count + 1
        End If
        'Clear measure when done
        HOperatorSet.CloseMeasure(msrHandle_Measure_1st)
        HOperatorSet.CloseMeasure(msrHandle_Measure_2nd)
        HOperatorSet.CloseMeasure(msrHandle_Measure_3rd)
        HOperatorSet.CloseMeasure(msrHandle_Measure_4th)
    End Sub

    Friend Sub FindReticle(ByRef pSourceImage As CImage, ByVal CentraX As Double, ByVal CentraY As Double)
        Dim amplitudeThreshold_1st As HTuple = New HTuple 'amplitude門檻值
        Dim roiWidthLen2_1st As HTuple = New HTuple 'ROI寬度 實際大小要放大兩倍
        Dim lineRowStart_Measure_1st As HTuple = New HTuple '線段ROW起始
        Dim lineColumnStart_Measure_1st As HTuple = New HTuple '線段COLUMN起始
        Dim lineRowEnd_Measure_1st As HTuple = New HTuple '線段ROW終點
        Dim lineColumnEnd_Measure_1st As HTuple = New HTuple '線段COLUMN終點
        Dim tmpCtrl_Row_1st As HTuple = New HTuple
        Dim tmpCtrl_Column_1st As HTuple = New HTuple
        Dim tmpCtrl_Dr_1st As HTuple = New HTuple
        Dim tmpCtrl_Dc_1st As HTuple = New HTuple
        Dim tmpCtrl_Phi_1st As HTuple = New HTuple
        Dim tmpCtrl_Len1_1st As HTuple = New HTuple
        Dim tmpCtrl_Len2_1st As HTuple = New HTuple
        Dim msrHandle_Measure_1st As HTuple = New HTuple
        Dim row_Measure_1st As HTuple = New HTuple
        Dim column_Measure_1st As HTuple = New HTuple
        Dim amplitude_Measure_1st As HTuple = New HTuple
        Dim distance_Measure_1st As HTuple = New HTuple

        Dim amplitudeThreshold_2nd As HTuple = New HTuple
        Dim roiWidthLen2_2nd As HTuple = New HTuple
        Dim lineRowStart_Measure_2nd As HTuple = New HTuple
        Dim lineColumnStart_Measure_2nd As HTuple = New HTuple
        Dim lineRowEnd_Measure_2nd As HTuple = New HTuple
        Dim lineColumnEnd_Measure_2nd As HTuple = New HTuple
        Dim tmpCtrl_Row_2nd As HTuple = New HTuple
        Dim tmpCtrl_Column_2nd As HTuple = New HTuple
        Dim tmpCtrl_Dr_2nd As HTuple = New HTuple
        Dim tmpCtrl_Dc_2nd As HTuple = New HTuple
        Dim tmpCtrl_Phi_2nd As HTuple = New HTuple
        Dim tmpCtrl_Len1_2nd As HTuple = New HTuple
        Dim tmpCtrl_Len2_2nd As HTuple = New HTuple
        Dim msrHandle_Measure_2nd As HTuple = New HTuple
        Dim row_Measure_2nd As HTuple = New HTuple
        Dim column_Measure_2nd As HTuple = New HTuple
        Dim amplitude_Measure_2nd As HTuple = New HTuple
        Dim distance_Measure_2nd As HTuple = New HTuple

        Dim amplitudeThreshold_3rd As HTuple = New HTuple
        Dim roiWidthLen2_3rd As HTuple = New HTuple
        Dim lineRowStart_Measure_3rd As HTuple = New HTuple
        Dim lineColumnStart_Measure_3rd As HTuple = New HTuple
        Dim lineRowEnd_Measure_3rd As HTuple = New HTuple
        Dim lineColumnEnd_Measure_3rd As HTuple = New HTuple
        Dim tmpCtrl_Row_3rd As HTuple = New HTuple
        Dim tmpCtrl_Column_3rd As HTuple = New HTuple
        Dim tmpCtrl_Dr_3rd As HTuple = New HTuple
        Dim tmpCtrl_Dc_3rd As HTuple = New HTuple
        Dim tmpCtrl_Phi_3rd As HTuple = New HTuple
        Dim tmpCtrl_Len1_3rd As HTuple = New HTuple
        Dim tmpCtrl_Len2_3rd As HTuple = New HTuple
        Dim msrHandle_Measure_3rd As HTuple = New HTuple
        Dim row_Measure_3rd As HTuple = New HTuple
        Dim column_Measure_3rd As HTuple = New HTuple
        Dim amplitude_Measure_3rd As HTuple = New HTuple
        Dim distance_Measure_3rd As HTuple = New HTuple


        Dim amplitudeThreshold_4th As HTuple = New HTuple
        Dim roiWidthLen2_4th As HTuple = New HTuple
        Dim lineRowStart_Measure_4th As HTuple = New HTuple
        Dim lineColumnStart_Measure_4th As HTuple = New HTuple
        Dim lineRowEnd_Measure_4th As HTuple = New HTuple
        Dim lineColumnEnd_Measure_4th As HTuple = New HTuple
        Dim tmpCtrl_Row_4th As HTuple = New HTuple
        Dim tmpCtrl_Column_4th As HTuple = New HTuple
        Dim tmpCtrl_Dr_4th As HTuple = New HTuple
        Dim tmpCtrl_Dc_4th As HTuple = New HTuple
        Dim tmpCtrl_Phi_4th As HTuple = New HTuple
        Dim tmpCtrl_Len1_4th As HTuple = New HTuple
        Dim tmpCtrl_Len2_4th As HTuple = New HTuple
        Dim msrHandle_Measure_4th As HTuple = New HTuple
        Dim row_Measure_4th As HTuple = New HTuple
        Dim column_Measure_4th As HTuple = New HTuple
        Dim amplitude_Measure_4th As HTuple = New HTuple
        Dim distance_Measure_4th As HTuple = New HTuple

        'Prepare measurement
        amplitudeThreshold_1st = New HTuple(6)
        roiWidthLen2_1st = 127.5

        '先往上找
        'Coordinates for line Measure
        lineRowStart_Measure_1st = New HTuple(CentraY + 50)
        lineColumnStart_Measure_1st = New HTuple(CentraX)
        lineRowEnd_Measure_1st = New HTuple(CentraY - 50)
        lineColumnEnd_Measure_1st = New HTuple(CentraX)


        'Convert coordinates to rectangle2 type
        tmpCtrl_Row_1st = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_1st.TupleAdd(lineRowEnd_Measure_1st))
        tmpCtrl_Column_1st = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_1st.TupleAdd(lineColumnEnd_Measure_1st))
        tmpCtrl_Dr_1st = lineRowStart_Measure_1st.TupleSub(lineRowEnd_Measure_1st)
        tmpCtrl_Dc_1st = lineColumnEnd_Measure_1st.TupleSub(lineColumnStart_Measure_1st)
        tmpCtrl_Phi_1st = tmpCtrl_Dr_1st.TupleAtan2(tmpCtrl_Dc_1st)
        tmpCtrl_Len1_1st = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_1st.TupleMult(tmpCtrl_Dr_1st))).TupleAdd(tmpCtrl_Dc_1st.TupleMult(tmpCtrl_Dc_1st)))).TupleSqrt())
        tmpCtrl_Len2_1st = roiWidthLen2_1st.Clone()
        'Create measure for line Measure
        'Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_1st, tmpCtrl_Column_1st, tmpCtrl_Phi_1st, _
                                          tmpCtrl_Len1_1st, tmpCtrl_Len2_1st, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("nearest_neighbor"), _
                                          msrHandle_Measure_1st)
        'Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_1st, New HTuple(1), amplitudeThreshold_1st, New HTuple("positive"), New HTuple("first"), row_Measure_1st, column_Measure_1st, amplitude_Measure_1st, distance_Measure_1st)


        'Prepare measurement
        amplitudeThreshold_2nd = New HTuple(6)
        roiWidthLen2_2nd = 100
        '往下找
        'Coordinates for line Measure
        lineRowStart_Measure_2nd = New HTuple(CentraY - 50)
        lineColumnStart_Measure_2nd = New HTuple(CentraX)
        lineRowEnd_Measure_2nd = New HTuple(CentraY + 50)
        lineColumnEnd_Measure_2nd = New HTuple(CentraX)


        'Convert coordinates to rectangle2 type
        tmpCtrl_Row_2nd = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_2nd.TupleAdd(lineRowEnd_Measure_2nd))
        tmpCtrl_Column_2nd = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_2nd.TupleAdd(lineColumnEnd_Measure_2nd))
        tmpCtrl_Dr_2nd = lineRowStart_Measure_2nd.TupleSub(lineRowEnd_Measure_2nd)
        tmpCtrl_Dc_2nd = lineColumnEnd_Measure_2nd.TupleSub(lineColumnStart_Measure_2nd)
        tmpCtrl_Phi_2nd = tmpCtrl_Dr_2nd.TupleAtan2(tmpCtrl_Dc_2nd)
        tmpCtrl_Len1_2nd = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_2nd.TupleMult(tmpCtrl_Dr_2nd))).TupleAdd(tmpCtrl_Dc_2nd.TupleMult(tmpCtrl_Dc_2nd)))).TupleSqrt())
        tmpCtrl_Len2_2nd = roiWidthLen2_2nd.Clone()
        'Create measure for line Measure
        'Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_2nd, tmpCtrl_Column_2nd, tmpCtrl_Phi_2nd, _
                                          tmpCtrl_Len1_2nd, tmpCtrl_Len2_2nd, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("nearest_neighbor"), _
                                          msrHandle_Measure_2nd)
        'Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_2nd, New HTuple(1), amplitudeThreshold_2nd, New HTuple("positive"), New HTuple("first"), row_Measure_2nd, column_Measure_2nd, amplitude_Measure_2nd, distance_Measure_2nd)


        'Prepare measurement
        amplitudeThreshold_3rd = New HTuple(6)
        roiWidthLen2_3rd = 100
        '往左找
        'Coordinates for line Measure
        lineRowStart_Measure_3rd = New HTuple(CentraY)
        lineColumnStart_Measure_3rd = New HTuple(CentraX + 50)
        lineRowEnd_Measure_3rd = New HTuple(CentraY)
        lineColumnEnd_Measure_3rd = New HTuple(CentraX - 50)


        'Convert coordinates to rectangle2 type
        tmpCtrl_Row_3rd = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_3rd.TupleAdd(lineRowEnd_Measure_3rd))
        tmpCtrl_Column_3rd = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_3rd.TupleAdd(lineColumnEnd_Measure_3rd))
        tmpCtrl_Dr_3rd = lineRowStart_Measure_3rd.TupleSub(lineRowEnd_Measure_3rd)
        tmpCtrl_Dc_3rd = lineColumnEnd_Measure_3rd.TupleSub(lineColumnStart_Measure_3rd)
        tmpCtrl_Phi_3rd = tmpCtrl_Dr_3rd.TupleAtan2(tmpCtrl_Dc_3rd)
        tmpCtrl_Len1_3rd = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_3rd.TupleMult(tmpCtrl_Dr_3rd))).TupleAdd(tmpCtrl_Dc_3rd.TupleMult(tmpCtrl_Dc_3rd)))).TupleSqrt())
        tmpCtrl_Len2_3rd = roiWidthLen2_3rd.Clone()
        'Create measure for line Measure
        'Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_3rd, tmpCtrl_Column_3rd, tmpCtrl_Phi_3rd, _
                                          tmpCtrl_Len1_3rd, tmpCtrl_Len2_3rd, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("nearest_neighbor"), _
                                          msrHandle_Measure_3rd)
        'Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_3rd, New HTuple(1), amplitudeThreshold_3rd, New HTuple("positive"), New HTuple("first"), row_Measure_3rd, column_Measure_3rd, amplitude_Measure_3rd, distance_Measure_3rd)


        'Prepare measurement
        amplitudeThreshold_4th = New HTuple(6)
        roiWidthLen2_4th = 100
        '往右找
        'Coordinates for line Measure
        lineRowStart_Measure_4th = New HTuple(CentraY)
        lineColumnStart_Measure_4th = New HTuple(0) ' New HTuple(CentraX)
        lineRowEnd_Measure_4th = New HTuple(CentraY)
        lineColumnEnd_Measure_4th = New HTuple(320) ' New HTuple(CentraX + 50)


        'Convert coordinates to rectangle2 type
        tmpCtrl_Row_4th = (New HTuple(0.5)).TupleMult(lineRowStart_Measure_4th.TupleAdd(lineRowEnd_Measure_4th))
        tmpCtrl_Column_4th = (New HTuple(0.5)).TupleMult(lineColumnStart_Measure_4th.TupleAdd(lineColumnEnd_Measure_4th))
        tmpCtrl_Dr_4th = lineRowStart_Measure_4th.TupleSub(lineRowEnd_Measure_4th)
        tmpCtrl_Dc_4th = lineColumnEnd_Measure_4th.TupleSub(lineColumnStart_Measure_4th)
        tmpCtrl_Phi_4th = tmpCtrl_Dr_4th.TupleAtan2(tmpCtrl_Dc_4th)
        tmpCtrl_Len1_4th = (New HTuple(0.5)).TupleMult(((((tmpCtrl_Dr_4th.TupleMult(tmpCtrl_Dr_4th))).TupleAdd(tmpCtrl_Dc_4th.TupleMult(tmpCtrl_Dc_4th)))).TupleSqrt())
        tmpCtrl_Len2_4th = roiWidthLen2_4th.Clone()
        'Create measure for line Measure
        'Attention: This assumes all images have the same size!
        HOperatorSet.GenMeasureRectangle2(tmpCtrl_Row_4th, tmpCtrl_Column_4th, tmpCtrl_Phi_4th, _
                                          tmpCtrl_Len1_4th, tmpCtrl_Len2_4th, New HTuple(pSourceImage.Width), New HTuple(pSourceImage.Height), New HTuple("nearest_neighbor"), _
                                          msrHandle_Measure_4th)
        'Execute measurements
        HOperatorSet.MeasurePos(pSourceImage.Based(), msrHandle_Measure_4th, New HTuple(1), amplitudeThreshold_4th, New HTuple("positive"), New HTuple("first"), row_Measure_4th, column_Measure_4th, amplitude_Measure_4th, distance_Measure_4th)


        'Do something with the results
        m_Count = 0
        If (row_Measure_1st.Length() > 0) AndAlso (row_Measure_2nd.Length() > 0) AndAlso (row_Measure_3rd.Length() > 0) AndAlso (row_Measure_4th.Length() > 0) Then
            Call m_Point.SetOriginEndPos(column_Measure_3rd.D(), row_Measure_1st.D(), column_Measure_4th.D(), row_Measure_2nd.D())
            m_Count = m_Count + 1
        End If
        'Clear measure when done
        HOperatorSet.CloseMeasure(msrHandle_Measure_1st)
        HOperatorSet.CloseMeasure(msrHandle_Measure_2nd)
        HOperatorSet.CloseMeasure(msrHandle_Measure_3rd)
        HOperatorSet.CloseMeasure(msrHandle_Measure_4th)
    End Sub
    #End Region
End Class
